apiVersion: apps/v1
kind: Deployment
metadata:
  name: yepp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yepp
  template:
    metadata:
      labels:
        app: yepp
    spec:
      containers:
      - name: yepp
        image: serieswatcher/yeppp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yepp-service
spec:
  selector:
    app: yepp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort
