apiVersion: apps/v1
kind: Deployment
metadata:
  name: archttyd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archttyd
  template:
    metadata:
      labels:
        app: archttyd
    spec:
      containers:
      - name: archttyd-container
        image: serieswatcher/arch-ttyd:latest
        ports:
        - containerPort: 7681
---

apiVersion: v1
kind: Service
metadata:
  name: archttyd-service
spec:
  selector:
    app: archttyd
  ports:
    - protocol: TCP
      port: 7681
      targetPort: 7681
      nodePort: 30002
  type: NodePort
