apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdew
  template:
    metadata:
      labels:
        app: asdew
    spec:
      containers:
      - name: asdew
        image: serieswatcher/asd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: asdew-service
spec:
  selector:
    app: asdew
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30126
  type: NodePort
