apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstone
  template:
    metadata:
      labels:
        app: firstone
    spec:
      containers:
      - name: firstone
        image: serieswatcher/first:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: firstone-service
spec:
  selector:
    app: firstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
