apiVersion: apps/v1
kind: Deployment
metadata:
  name: newone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newone
  template:
    metadata:
      labels:
        app: newone
    spec:
      containers:
      - name: newone
        image: serieswatcher/newone:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: newone-service
spec:
  selector:
    app: newone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
