apiVersion: apps/v1
kind: Deployment
metadata:
  name: woah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: woah
  template:
    metadata:
      labels:
        app: woah
    spec:
      containers:
      - name: woah
        image: serieswatcher/woah:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: woah-service
spec:
  selector:
    app: woah
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
  type: NodePort
