apiVersion: apps/v1
kind: Deployment
metadata:
  name: Saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Saas
  template:
    metadata:
      labels:
        app: Saas
    spec:
      containers:
      - name: Saas
        image: nextcloud
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Saas-service
spec:
  selector:
    app: Saas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30512
  type: NodePort
