apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextv1
  template:
    metadata:
      labels:
        app: nextv1
    spec:
      containers:
      - name: nextv1
        image: nextcloud
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextv1-service
spec:
  selector:
    app: nextv1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30031
  type: NodePort
