apiVersion: apps/v1
kind: Deployment
metadata:
  name: dodod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dodod
  template:
    metadata:
      labels:
        app: dodod
    spec:
      containers:
      - name: dodod
        image: serieswatcher/ffffff:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dodod-service
spec:
  selector:
    app: dodod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30123
  type: NodePort
