apiVersion: apps/v1
kind: Deployment
metadata:
  name: sss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sss
  template:
    metadata:
      labels:
        app: sss
    spec:
      containers:
      - name: sss
        image: serieswatcher/sss:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sss-service
spec:
  selector:
    app: sss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009
  type: NodePort
