# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ttyd-service
spec:
  selector:
    app: ttyd
  ports:
    - protocol: TCP
      port: 30018  # Use any available port on your cluster
      targetPort: 7681
  type: NodePort
