apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempp
  template:
    metadata:
      labels:
        app: tempp
    spec:
      containers:
      - name: tempp
        image: serieswatcher/tempp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tempp-service
spec:
  selector:
    app: tempp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30019
  type: NodePort
