apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30028 # Choose a suitable nodePort
  selector:
    app: wordpress

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30029  # Choose a suitable nodePort
  selector:
    app: mariadb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: wordpress-mariadb
  labels:
    app: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:latest
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: localhost
        - name: WORDPRESS_DB_PASSWORD
          value: your-db-password
    - name: mariadb
      image: mariadb:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: your-db-root-password
  volumes:
    - name: mariadb-persistent-storage
      persistentVolumeClaim:
        claimName: mariadb-pv-claim
