apiVersion: apps/v1
kind: Deployment
metadata:
  name: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latest
  template:
    metadata:
      labels:
        app: latest
    spec:
      containers:
      - name: latest
        image: serieswatcher/final:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: latest-service
spec:
  selector:
    app: latest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
