apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfg
  template:
    metadata:
      labels:
        app: gfg
    spec:
      containers:
      - name: gfg
        image: serieswatcher/fgf:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gfg-service
spec:
  selector:
    app: gfg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30019
  type: NodePort
