apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80           # Port exposed by the service
      targetPort: 80     # Port the container listens on
      nodePort: 30020    # Port accessible on each cluster node
  selector:
    app: website         # Label selector to match the deployment
