apiVersion: apps/v1
kind: Deployment
metadata:
  name: presi4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presi4
  template:
    metadata:
      labels:
        app: presi4
    spec:
      containers:
      - name: presi4
        image: serieswatcher/presi4:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: presi4-service
spec:
  selector:
    app: presi4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
