apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment  # Corrected the name to adhere to naming conventions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend  # Added the missing label
  template:
    metadata:
      labels:
        app: second-app
        tier: backend  # Added the missing label to match the selector
    spec:
      containers:
      - name: second-node
        image: serieswatcher/kubetest:2
