apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
      - name: first
        image: serieswatcher/first:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: first
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30016
  type: NodePort
