apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ss
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: ss
        image: serieswatcher/ss:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ss-service
spec:
  selector:
    app: ss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 3008
  type: NodePort
