apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubu
  template:
    metadata:
      labels:
        app: ubu
    spec:
      containers:
      - name: ubu
        image: serieswatcher/ubuntu:latest
        ports:
        - containerPort: 6901
        env:
        - name: VNC_PW
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: ubu-service
spec:
  selector:
    app: ubu
  ports:
    - protocol: TCP
      port: 6901
      targetPort: 6901
      nodePort: 30005
  type: NodePort
